### ISSUE TITLE
Quickbooks Point of sale qbactivator

### ISSUE THREAD

**Issue by sdeb19** [neuralpain/qbactivator#14] opened 2023-07-02 17:38 UTC
Please assist.
I've download everything as discussed but keep on getting an error " we sorry qbpos HAS RUN INTO A PROBLEM. PLEASE RESTART THE PROGRAM.
My PC run on windows 11
I've restarts the program.
Restart my laptop but the problem is the same.
The program stuck just after do not check for updates. 
[image](https://github.com/neuralpain/qbactivator/assets/138392609/bb35ee73-25fd-4cce-b546-3c9c49a1f493) 

Looking forward to hear from your soon

**Comment by Harmonygrams** [comment] 2023-07-08 02:56
Brother check out 
https://youtu.be/3DpfeylcgOM
Also their website: slaiz.link

They are simply the best. I tried this github repository but it didn't work so I reached out to them and got quickbooks installed. All the best

**Comment by neuralpain** [comment] 2023-07-09 19:23
Hello. It sounds like the software was installed correctly but please do a clean reinstall of the POS software if you are still receiving issues.

**Comment by neuralpain** [comment] 2023-08-16 01:41
After a review/troubleshoot with issue #21, this QuickBooks issue is not one that can be fixed without re-installing your Windows operating system. It's not yet determined what may be the cause of this issue so this is the only solution I can offer right now to this specific QuickBooks problem.

**Closed by neuralpain** 2023-08-16 01:41 UTC
